      SUBROUTINE     set_name()

      implicit none

      include "parameter.h"
      include "variable.h"
      include "common.h"

      atom_name(0)    =  'Lp'

      atom_name(1)    =  'H'
      atom_name(2)    =  'He'
      atom_name(3)    =  'Li'
      atom_name(4)    =  'Be'
      atom_name(5)    =  'B'
      atom_name(6)    =  'C'
      atom_name(7)    =  'N'
      atom_name(8)    =  'O'
      atom_name(9)    =  'F'
      atom_name(10)   =  'Ne'
      atom_name(11)   =  'Na'
      atom_name(12)   =  'Mg'
      atom_name(13)   =  'Al'
      atom_name(14)   =  'Si'
      atom_name(15)   =  'P'
      atom_name(16)   =  'S'
      atom_name(17)   =  'Cl'
      atom_name(18)   =  'K'
      atom_name(19)   =  'Ar'
      atom_name(20)   =  'Ca'

      atom_name(21)   =  'Sc'
      atom_name(22)   =  'Ti'
      atom_name(23)   =  'V'
      atom_name(24)   =  'Cr'
      atom_name(25)   =  'Mn'
      atom_name(26)   =  'Fe'
      atom_name(27)   =  'Ni'
      atom_name(28)   =  'Co'
      atom_name(29)   =  'Cu'
      atom_name(30)   =  'Zn'
      atom_name(31)   =  'Ga'
      atom_name(32)   =  'Ge'
      atom_name(33)   =  'As'
      atom_name(34)   =  'Se'
      atom_name(35)   =  'Br'
      atom_name(36)   =  'Kr'
      atom_name(37)   =  'Ru'
      atom_name(38)   =  'St'
      atom_name(39)   =  'Y'
      atom_name(40)   =  'Zr'

      atom_name(41)   =  'Nb'
      atom_name(42)   =  'Mo'
      atom_name(43)   =  'Tc'
      atom_name(44)   =  'Ru'
      atom_name(45)   =  'Rh'
      atom_name(46)   =  'Pd'
      atom_name(47)   =  'Ag'
      atom_name(48)   =  'Cd'
      atom_name(49)   =  'In'
      atom_name(50)   =  'Sn'
      atom_name(51)   =  'Sb'
      atom_name(52)   =  'I'
      atom_name(53)   =  'Te'
      atom_name(54)   =  'Xe'
      atom_name(55)   =  'Cs'
      atom_name(56)   =  'Ba'
      atom_name(57)   =  'La'
      atom_name(58)   =  'Ce'
      atom_name(59)   =  'Pr'
      atom_name(60)   =  'Nd'

      atom_name(61)   =  'Pm'
      atom_name(62)   =  'Sm'
      atom_name(63)   =  'Eu'
      atom_name(64)   =  'Gd'
      atom_name(65)   =  'Tb'
      atom_name(66)   =  'Dy'
      atom_name(67)   =  'Ho'
      atom_name(68)   =  'Er'
      atom_name(69)   =  'Tm'
      atom_name(70)   =  'Yb'
      atom_name(71)   =  'Lu'
      atom_name(72)   =  'Hf'
      atom_name(73)   =  'Ta'
      atom_name(74)   =  'W'
      atom_name(75)   =  'Re'
      atom_name(76)   =  'Os'
      atom_name(77)   =  'Ir'
      atom_name(78)   =  'Pt'
      atom_name(79)   =  'Au'
      atom_name(80)   =  'Hg'

      atom_name(81)   =  'Ti'
      atom_name(82)   =  'Pb'
      atom_name(83)   =  'Bi'
      atom_name(84)   =  'Po'
      atom_name(85)   =  'At'
      atom_name(86)   =  'Rn'
      atom_name(87)   =  'Fr'
      atom_name(88)   =  'Ra'
      atom_name(89)   =  'Ac'
      atom_name(90)   =  'Pa'
      atom_name(91)   =  'Th'
      atom_name(92)   =  'Np'
      atom_name(93)   =  'U'
      atom_name(94)   =  'Am'
      atom_name(95)   =  'Pu'
      atom_name(96)   =  'Cm'
      atom_name(97)   =  'Bk'
      atom_name(98)   =  'Cf'
      atom_name(99)   =  'Es'
      atom_name(100)  =  'Fm'

      atom_name(101)  =  'Md'
      atom_name(102)  =  'No'
      atom_name(103)  =  'Rf'
      atom_name(104)  =  'Lr'
      atom_name(105)  =  'Db'
      atom_name(106)  =  'Bh'
      atom_name(107)  =  'Sg'
      atom_name(108)  =  'Mt'
      atom_name(109)  =  'Rg'
      atom_name(110)  =  'Hs'
      atom_name(111)  =  'Ds'
      atom_name(112)  =  'Uub'
      atom_name(113)  =  'Uut'
      atom_name(114)  =  'Uuq'
      atom_name(115)  =  'Uup'
      atom_name(116)  =  'Uuh'
      atom_name(117)  =  'Uus'
      atom_name(118)  =  'Uuo'
      atom_name(119)  =  'NAY'
      atom_name(120)  =  'NAY'

      END
